- platform: fastdotcom 

- platform: darksky
  api_key: !secret dark_sky_api_key
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - nearest_storm_bearing
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
    - precip_intensity_max

  #zwave sensors
- platform: template
  sensors:
    hall_multi_batt:
      value_template: '{{ states.sensor.vision_zp3111_multisensor_4in1_burglar_9_10.attributes.battery_level }}'
      unit_of_measurement: '%'
    hall_multi_lum:
      value_template: '{{ states.sensor.vision_zp3111_multisensor_4in1_luminance_9_3.state }}'
      unit_of_measurement: '%'
    hall_multi_temp:
      value_template: '{{ states.sensor.vision_zp3111_multisensor_4in1_temperature_9_1.state | int}}'
      unit_of_measurement: '°F'
    hall_multi_humiditiy:
      value_template: '{{ states.sensor.vision_zp3111_multisensor_4in1_relative_humidity_9_5.state | int }}'
      unit_of_measurement: '%'
    zte_batt:
      value_template: '{{ states.device_tracker.pi_md.attributes.battery }}'
      unit_of_measurement: '%'
